name: primebroward-crm
region: nyc

services:
  - name: api
    github:
      repo: kebson01/PrimeBrowardCRM
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile.api
    http_port: 8000
    instance_count: 1
    instance_size_slug: professional-xs
    envs:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    health_check:
      http_path: /api/health
      port: 8000

  - name: frontend
    github:
      repo: kebson01/PrimeBrowardCRM
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile.frontend
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: "production"
