name: primebroward-crm
region: nyc

services:
  - name: api
    type: service
    github:
      repo: kebson01/PrimeBrowardCRM
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.api
    build_command: echo "Building with Docker"
    run_command: /start.sh
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: PORT
        value: "8000"
      - key: API_HOST
        value: "0.0.0.0"
      - key: API_PORT
        value: "8000"
      - key: DATABASE_PATH
        value: "/app/data/primebroward.db"
      - key: DATA_DIR
        value: "/app/data"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CORS_ORIGINS
        value: "*"
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5

  - name: frontend
    type: service
    github:
      repo: kebson01/PrimeBrowardCRM
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile.frontend
    build_command: echo "Building with Docker"
    run_command: /start.sh
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: "production"
